### ISSUE TITLE
 throw new Error("Sorry, your browser doesn't support WebGL.");

### ISSUE THREAD

**Issue by biandh** [tnfe/FFCreator#1]
/Users/Downloads/FFCreator-master/node_modules/spritejs/dist/spritejs.js:10884
    throw new Error("Sorry, your browser doesn't support WebGL.");
     ^
Error: Sorry, your browser doesn't support WebGL.
    at setupWebGL (/Users/Downloads/FFCreator-master/node_modules/spritejs/dist/spritejs.js:10884:11)
    at new Renderer (/Users/Downloads/FFCreator-master/node_modules/spritejs/dist/spritejs.js:9012:71)
    at new Renderer (/Users/Downloads/FFCreator-master/node_modules/spritejs/dist/spritejs.js:8070:22)
    at new Layer (/Users/Downloads/FFCreator-master/node_modules/spritejs/dist/spritejs.js:37719:24)
    at /Users/Downloads/FFCreator-master/lib/node/cons.js:31:21
    at Object.get (/Users/Downloads/FFCreator-master/lib/core/pool.js:19:63)
    at FFCreator.createDisplay (/Users/Downloads/FFCreator-master/lib/node/cons.js:30:25)
    at new FFCon (/Users/Downloads/FFCreator-master/lib/node/cons.js:22:10)
    at new FFCreator (/Users/Downloads/FFCreator-master/lib/creator.js:35:5)

Chrome version 86.0.4240.193   
this support WEBGL when I open some test webgl available webpage
mac os 10.13.4

**Comment by drawcall** [comment]
Oh, FFCreator needs to be run in the node.js back-end project. Did you run it in the front-end project?
