### ISSUE TITLE
4.3.3版本中，是否存在为图片或者视频设置某些动画，比如说”bounceIn“之后，为它主动设置的宽度与长度无效化的情况？

### ISSUE THREAD

**Issue by zhuzengguan** [tnfe/FFCreator#100]

**Comment by drawcall** [comment]
Please paste your code or upload the project

**Comment by zhuzengguan** [comment]
> Please paste your code or upload the project
let fbg = new FFImage({
                        path: 'D:/elephant.png',
                        width: 400,
                        height: 300,
                        x: 1280/2,
                        y: 960/2,
                         
                       
                });
                fbg.addEffect('bounceIn',1,1)
                scene.addChild(fbg)  
情况就是width与height会不生效，如果将'bounceIn'替换成’‘fadeInUpBig”则可以设置width与height
万分感谢！

**Comment by drawcall** [comment]
Please download the latest version it has been fixed.

**Comment by zhuzengguan** [comment]
> Please download the latest version it has been fixed.

抱歉，今天早上更新了版本之后，出现了报错：
TypeError: Cannot read property 'copy' of undefined
      at FFImage.setDisplaySize (D:\ave\ave-vre-server\trunk\core\libs\ffcreator\node\/image.js:90:25)
      at FFImage.createDisplay (D:\ave\ave-vre-server\trunk\core\libs\ffcreator\node\/image.js:39:10)
      at new FFNode (D:\ave\ave-vre-server\trunk\core\libs\ffcreator\node\/node.js:42:10)
      at new FFImage (D:\ave\ave-vre-server\trunk\core\libs\ffcreator\node\/image.js:19:5)
      at Object.addBgResouce (D:\ave\ave-vre-server\trunk\core\utils\/scens-toolkits-new.js:311:23)
      at Actuator20010000.createFFTask (D:\ave\ave-vre-server\trunk\core\actuators\/actuator20010000.js:95:31)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
}
可以请问一下是否代码未更新完全呢
