### ISSUE TITLE
请问一下最新版本的报错问题

### ISSUE THREAD

**Issue by zhuzengguan** [tnfe/FFCreator#103]
抱歉，今天早上更新了版本之后，出现了报错：
TypeError: Cannot read property 'copy' of undefined
at FFImage.setDisplaySize (D:\ave\ave-vre-server\trunk\core\libs\ffcreator\node/image.js:90:25)
at FFImage.createDisplay (D:\ave\ave-vre-server\trunk\core\libs\ffcreator\node/image.js:39:10)
at new FFNode (D:\ave\ave-vre-server\trunk\core\libs\ffcreator\node/node.js:42:10)
at new FFImage (D:\ave\ave-vre-server\trunk\core\libs\ffcreator\node/image.js:19:5)
at Object.addBgResouce (D:\ave\ave-vre-server\trunk\core\utils/scens-toolkits-new.js:311:23)
at Actuator20010000.createFFTask (D:\ave\ave-vre-server\trunk\core\actuators/actuator20010000.js:95:31)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
}
可以请问一下是否代码未更新完全呢
万分感谢！

**Comment by zhuzengguan** [comment]
以及请问 如果添加一个视频画中画元素，也存在动画重置大小问题，那么该视频元素的动画重置问题是否也能使用initScale属性来解决呢

**Comment by drawcall** [comment]
v4.5.1?

**Comment by zhuzengguan** [comment]
> v4.5.1? I think you need clean npm cache.

感谢你的提醒，我升级了‘inkpaint’版本之后解决了报错问题，图片的动画重置大小问题已经解决，但是视频元素的动画重置大小问题似乎依然存在

  let sb1_fvideo = new FFVideo({
                    path: videoPath,
                    width: 400,
                    height: 400,
                    x: 760,
                    y: 680,
                    });
                    sb1_fvideo.addEffect('bounceIn',1,1)
                    scene.addChild(sb1_fvideo)
其中的width以及height设置似乎并不能成功使视频缩小或放大

**Comment by drawcall** [comment]
great, you can submit a pr.

**Comment by zhuzengguan** [comment]
> great, you can submit a pr. Oh, maybe you can use lowcode and ffcreator to create a visual creation video site.

This is a great idea and thank you for your great contribution.

**Comment by Shijiuwei** [comment]
你好，发现 FFAlbum 也有这个问题，相册里的图片也有 scale 的问题。

**Comment by Shijiuwei** [comment]
lib/node/album.js createSingleImage 方法内最后加了 sprite.initScale && sprite.initScale.copy(sprite.scale);  解决了
