### ISSUE TITLE
[咨询]请问支持实时视频流的输入输出么？

### ISSUE THREAD

**Issue by limjoe** [tnfe/FFCreator#108]
目前有个需求: 处理实时视频流 rtmp 的输入, 然后同时添加图片水印、音乐，然后将结果以实时视频流的方式推送到其他流媒体服务。

我使用 ffmpeg 单独跑通了 
1. 实时视频流+图片=实时视频流输出
2. 实时视频流+mp3=实时视频流输出

但是两者同时处理没有跑通，看到此库似乎匹配我的需求，但是似乎都是针对离线处理视频的场景

**Comment by drawcall** [comment]
Oh, you can try to modify[ffcreatorlite](https://github.com/tnfe/FFCreatorLite), it does not currently support this. ffcreatorlite is a combination of ffmpeg commands

**Comment by limjoe** [comment]
我看了下你们代码，live.js 是支持实时视频流操作，但是不是一个流式处理的流程，第一步是 stream + text -> 0mp4 , 第二步是 0mp4 + audio = result

如果要同时添加图片和音频文件，是不是在同一个 ffmpeg 命令下搞不定的，需要拆分为2个 ffmpeg 命令，然后用 `|` 管道操作来拼接两步的输入输出

**Comment by drawcall** [comment]
https://github.com/tnfe/FFCreatorLite/blob/master/examples/live.js

I don’t know what effect you need, maybe you can use it. ffcreatorlite supports adding music and pictures at the same time

**Comment by limjoe** [comment]
其实我的场景就是对直播视频流，实时增加文字、图片、背景音乐，然后实时输出到流媒体分发出去

我看你新增了对 liveStream 的 commit， 目前跑 example/live.js ffmpeg 会报错

```
FFCreatorLite start
single: ffmpeg -loop 1 -i /Users/joe/Workspace/SENSORO-VMS/FFCreatorLite/examples/assets/imgs/wallp/06.jpeg -i  rtmp://xxxx -loop 1 -i /Users/joe/Workspace/SENSORO-VMS/FFCreatorLite/examples/assets/imgs/06.png -filter_complex color=c=#9980fa:d=17:size=700*500[background2-0];[background2-0][0:v]overlay=x=50:y=50[image1-1];[1:v]scale=iw*0.3:ih*0.3[live1-1];[live1-1]fade=type=in:st=3.5:d=2.5:color=black:alpha=1[live1-2];[image1-1][live1-2]overlay=x='if(between(t,3.5,6),200-200*(t-3.5)/2.5+100*pow((t-3.5)/2.5,2),100)':y='if(between(t,3.5,6),100+0*(t-3.5)/2.5-0*pow((t-3.5)/2.5,2),100)':enable='between(t,3.5,99999)'[live1-3];[2:v]fade=type=in:st=0:d=1.5:color=black:alpha=1[image2-1];[live1-3][image2-1]overlay=x='if(between(t,0,1.5),-180+200*t/1.5-100*pow(t/1.5,2),-80)':y='if(between(t,0,1.5),80+0*t/1.5-0*pow(t/1.5,2),80)'[image2-2];[image2-2]drawtext=bordercolor=#000000:borderw=5:fontcolor=#ffffff:fontfile=/Users/joe/Workspace/SENSORO-VMS/FFCreatorLite/examples/assets/font/scsf.ttf:fontsize=42:text=FFLive案例:x=230:y=100:eble='between(t,0,99999)'[text1-1] -map [text1-1] -r 24 -map 0 -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -f flv rtmp://192.168.3.2/live/h264Stream
==============
Error: ffmpeg exited with code 1: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 
Conversion failed!

    at ChildProcess.<anonymous> (/Users/joe/Workspace/SENSORO-VMS/FFCreatorLite/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
FFCreatorLite error:: 
 Error: ffmpeg exited with code 1: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 
Conversion failed!

```

**Comment by limjoe** [comment]
其实我的场景就是对直播视频流，实时增加文字、图片、背景音乐，然后实时输出到流媒体分发出去

我看你新增了对 liveStream 的 commit， 目前跑 example/live.js ffmpeg 会报错

```
FFCreatorLite start
single: ffmpeg -loop 1 -i /Users/joe/Workspace/VMS/FFCreatorLite/examples/assets/imgs/wallp/06.jpeg -i  rtmp://xxxx -loop 1 -i /Users/joe/Workspace/VMS/FFCreatorLite/examples/assets/imgs/06.png -filter_complex color=c=#9980fa:d=17:size=700*500[background2-0];[background2-0][0:v]overlay=x=50:y=50[image1-1];[1:v]scale=iw*0.3:ih*0.3[live1-1];[live1-1]fade=type=in:st=3.5:d=2.5:color=black:alpha=1[live1-2];[image1-1][live1-2]overlay=x='if(between(t,3.5,6),200-200*(t-3.5)/2.5+100*pow((t-3.5)/2.5,2),100)':y='if(between(t,3.5,6),100+0*(t-3.5)/2.5-0*pow((t-3.5)/2.5,2),100)':enable='between(t,3.5,99999)'[live1-3];[2:v]fade=type=in:st=0:d=1.5:color=black:alpha=1[image2-1];[live1-3][image2-1]overlay=x='if(between(t,0,1.5),-180+200*t/1.5-100*pow(t/1.5,2),-80)':y='if(between(t,0,1.5),80+0*t/1.5-0*pow(t/1.5,2),80)'[image2-2];[image2-2]drawtext=bordercolor=#000000:borderw=5:fontcolor=#ffffff:fontfile=/Users/joe/Workspace/VMS/FFCreatorLite/examples/assets/font/scsf.ttf:fontsize=42:text=FFLive案例:x=230:y=100:eble='between(t,0,99999)'[text1-1] -map [text1-1] -r 24 -map 0 -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -f flv rtmp://192.168.3.2/live/h264Stream
==============
Error: ffmpeg exited with code 1: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 
Conversion failed!

    at ChildProcess.<anonymous> (/Users/joe/Workspace/VMS/FFCreatorLite/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
FFCreatorLite error:: 
 Error: ffmpeg exited with code 1: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 
Conversion failed!

```

**Comment by limjoe** [comment]
此问题转至 ffcreatorlite [issues](https://github.com/tnfe/FFCreatorLite/issues/12) , 关闭此 issues
