### ISSUE TITLE
4.x和5.x版本 FFVtuber 不再可用，原因如下。

### ISSUE THREAD

**Issue by whl88** [tnfe/FFCreator#111]
## 样例代码

```javascript
_createHuman(){
    const human = new FFVtuber({
        x:700,
        y:850,
        scale:0.65,
    })
    human.setPath(this.param.human,1,6365)
    human.setSpeed(1)
    this.addChild(human)
}
```

## 报错信息

```javascript
(node:15288) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined    at new AnimatedSprite (D:\workspace\nodejs\xiaozhushou-generator\node_modules\_inkpaint@2.5.1@inkpaint\lib\sprites\AnimatedSprite.js:22:19)
    at FFVtuber.createDisplay (D:\workspace\nodejs\xiaozhushou-generator\node_modules\_ffcreator@5.2.7@ffcreator\lib\node\vtuber.js:53:20)
    at new FFNode (D:\workspace\nodejs\xiaozhushou-generator\node_modules\_ffcreator@5.2.7@ffcreator\lib\node\node.js:42:10)
    at new FFImage (D:\workspace\nodejs\xiaozhushou-generator\node_modules\_ffcreator@5.2.7@ffcreator\lib\node\image.js:19:5)
    at new FFVtuber (D:\workspace\nodejs\xiaozhushou-generator\node_modules\_ffcreator@5.2.7@ffcreator\lib\node\vtuber.js:23:5)
    at SegmentScene._createHuman (D:\workspace\nodejs\xiaozhushou-generator\task\ai-energize\scenes\segmentScene.js:99:19)
    at SegmentScene._init (D:\workspace\nodejs\xiaozhushou-generator\task\ai-energize\scenes\segmentScene.js:23:10)
    at new SegmentScene (D:\workspace\nodejs\xiaozhushou-generator\task\ai-energize\scenes\segmentScene.js:11:10)
    at createAi (D:\workspace\nodejs\xiaozhushou-generator\task\ai-energize\task.js:32:20)
    at Object.<anonymous> (D:\workspace\nodejs\xiaozhushou-generator\task\ai-energize\index.js:6:1)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## 问题代码

ffcreator/lib/node/vtuber.js:53 下图中的构造涵数没有给参数。
![image-20210917135331818](https://user-images.githubusercontent.com/28629101/133732102-5041add9-cb76-4d3e-a5c6-63b50528d7c3.png)
![image-20210917135431141](https://user-images.githubusercontent.com/28629101/133732117-3290ce07-51c8-4e14-b266-283526e53a35.png)

**Comment by drawcall** [comment]
Oh yes, after thinking about it again, I don’t think FFVtuber can be satisfied because it can’t keep your mouth. Maybe I will remove it later.

**Comment by whl88** [comment]
啊！大神，能不能修复一下，不删啊。我们非常需要这个功能。口型的问题我们可以解决，目前只能通过 FFVtuber 的方式向视频里添加带有透明通道的视频。拜托了。

**Comment by drawcall** [comment]
Oh, I upgraded FFVtuber, and now it supports green screen video vtuber. The sequence frames is not flexible.

https://github.com/tnfe/FFCreator/blob/master/examples/vtuber.js

**Comment by whl88** [comment]
great , thank you very much !!
