### ISSUE TITLE
使用egg框架，生产模式部署报错

### ISSUE THREAD

**Issue by hjane** [tnfe/FFCreator#152]
我node使用egg框架，服务器centos7，ffmpeg安装成功。
目前遇到问题
我在服务器以开发模式运行的时候一切正常。
xvfb-run -s "-ac -screen 0 1280x1024x24" yarn dev
yarn run v1.22.15
$ egg-bin dev
[egg-bin] server port 7001 is in use, now using port 7002
......

我以生产模式部署，则会报错。
xvfb-run -s "-ac -screen 0 1280x1024x24" yarn startyarn run v1.22.15
$ eggctl start --port=7001 --daemon --env=prod --title=egg-server-zhipianxing

ERROR 32766 nodejs.TypeError: Cannot read property 'ARRAY_BUFFER' of null
    at FFTransition.createBuffer (/www/wwwroot/zhipianxing/zhipianxing-node/node_modules/ffcreator/lib/animate/transition.js:73:45)
    at FFTransition.createTransition (/www/wwwroot/zhipianxing/zhipianxing-node/node_modules/ffcreator/lib/animate/transition.js:61:10)
    at FFTransition.bindGL (/www/wwwroot/zhipianxing/zhipianxing-node/node_modules/ffcreator/lib/animate/transition.js:40:10)
    at /www/wwwroot/zhipianxing/zhipianxing-node/node_modules/ffcreator/lib/core/renderer.js:119:57
    at arrayEach (/www/wwwroot/zhipianxing/zhipianxing-node/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/www/wwwroot/zhipianxing/zhipianxing-node/node_modules/lodash/forEach.js:38:10)
    at Renderer.transBindGL (/www/wwwroot/zhipianxing/zhipianxing-node/node_modules/ffcreator/lib/core/renderer.js:119:5)
    at Renderer.start (/www/wwwroot/zhipianxing/zhipianxing-node/node_modules/ffcreator/lib/core/renderer.js:55:10)

pid: 32766
hostname: iZ8vbek68af6xbyqmspit7Z

不知道有没有人遇到和我一样的问题，求解决方案！

**Comment by kaykie** [comment]
同样的问题 你解决了吗?
应该是在运行生产命令的时候,虽然你运行了服务,但是你的框架在运行完服务后 并没有把xvfb-run 运行的命令在后台保持运行,所以导致报错  问题应该出在xvfb-run 上 试着看看xvfb-run吧

**Comment by hjane** [comment]
> 同样的问题 你解决了吗? 应该是在运行生产命令的时候,虽然你运行了服务,但是你的框架在运行完服务后 并没有把xvfb-run 运行的命令在后台保持运行,所以导致报错 问题应该出在xvfb-run 上 试着看看xvfb-run吧

目前知道xvfb只是用于增加一个显示设备给headless-gl做输出绑定，用到headless-gl，就需要xvfb-run -s "-ac -screen 0 1280x1024x24" xxxx 这样启动。

我自己分析，daemon是守护进程，如果应用挂了会重启服务，我觉得加上后，可能它有自己启动方式，导致xvfb-run 之间的绑定关系丢失。

目前我没有找到可用的解决方案，我现在把ffcreator的相关业务抽离出来，单独起一个项目折腾。看能不能解决后台运行的问题。我也考虑过nodejs 调shell命令，直接用 xvfb-run -s "-ac -screen 0 1280x1024x24" node xxxx.js来执行，但发现这样就不可控了。

我去egg那边问，也是建议我去看看xvfb-run的实践……T T

这个是我找到的关于这个问题的另一个帖子，你也可以关注下。
[https://github.com/tnfe/FFCreator/issues/53](url)

**Comment by kaykie** [comment]
@hjane 
后面我找到解决方案了  可以使用 xvfb包  
写了篇博文   https://blog.csdn.net/qq_40913592/article/details/121626472 还没弄好可以参考一下
