### ISSUE TITLE
关于NVIDIA GPU 环境配置

### ISSUE THREAD

**Issue by 121786404** [tnfe/FFCreator#168]
ubutnu 2004 安装了如下的包 ，有一块RTX2080的显卡

apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev 
apt-get install libglvnd-dev libgl1-mesa-dev 

如果用GPU的话是不是不需要安装 xvfb ？

请问：如何能把GPU请起来？

npm run examples

> ffcreator@6.4.2 examples
> node ./examples/

? Please select the demo you want to run: (1) Picture animation video

 --- You can press the s key or the w key to restart! --- 

FFCreator start
/home/xxx/tmp/FFCreator/lib/animate/transition.js:73
    this.buffer = createBuffer(gl, data, gl.ARRAY_BUFFER, gl.STATIC_DRAW);
                                            ^

TypeError: Cannot read properties of null (reading 'ARRAY_BUFFER')
    at FFTransition.createBuffer (/home/xxx/tmp/FFCreator/lib/animate/transition.js:73:45)
    at FFTransition.createTransition (/home/xxx/tmp/FFCreator/lib/animate/transition.js:61:10)
    at FFTransition.bindGL (/home/xxx/tmp/FFCreator/lib/animate/transition.js:40:10)
    at /home/xxx/tmp/FFCreator/lib/core/renderer.js:119:57
    at arrayEach (/home/xxx/tmp/FFCreator/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/home/xxx/tmp/FFCreator/node_modules/lodash/forEach.js:38:10)
    at Renderer.transBindGL (/home/xxx/tmp/FFCreator/lib/core/renderer.js:119:5)
    at Renderer.start (/home/xxx/tmp/FFCreator/lib/core/renderer.js:55:10)

Node.js v17.3.1

**Comment by Vinlic** [comment]
可能只是没有XServer？如果想要在渲染时调用GPU你可能需要编译一个可以使用该显卡加速的FFmpeg

**Comment by 121786404** [comment]
ffmpeg 调用nvenc 我已经调通了，
你说的xserver 是指  apt install xserver-xorg-video-nvidia-495 吗

**Comment by 121786404** [comment]
另外 按照理解   libgl1-mesa-dev 是开源的opengl驱动，应该不用装，可是不安装的话 npm i ffcreator --save 就报错了

**Comment by tdcr5** [comment]
我也遇到类似的问题，楼主解决了么

**Comment by 121786404** [comment]
> 我也遇到类似的问题，楼主解决了么

没有
