### ISSUE TITLE
制作视频时报错

### ISSUE THREAD

**Issue by mcl0626** [tnfe/FFCreator#197]
Error: Texture Error: frame does not fit inside the base Texture dimensions: X: 0 + 1920 = 1920 > 1080 or Y: 28 + 1024 = 1052 > 1920

**Comment by mcl0626** [comment]
是因为视频宽高超出范围了吗？这个最大宽高范围可以改吗？

**Comment by mcl0626** [comment]
Error: Texture Error: frame does not fit inside the base Texture dimensions: X: 0 + 1920 = 1920 > 1080 or Y: 290 + 499 = 789 > 1920
    at Texture.set frame [as frame] (/www/wwwroot/fc/FFCreator-master/node_modules/inkpaint/lib/textures/Texture.js:241:13)
    at Texture.onBaseTextureLoaded (/www/wwwroot/fc/FFCreator-master/node_modules/inkpaint/lib/textures/Texture.js:144:18)
    at BaseTexture.emit (/www/wwwroot/fc/FFCreator-master/node_modules/inkpaint/node_modules/eventemitter3/index.js:129:35)
    at source.onload (/www/wwwroot/fc/FFCreator-master/node_modules/inkpaint/lib/textures/BaseTexture.js:101:14)
    at setSource (/www/wwwroot/fc/FFCreator-master/node_modules/canvas/lib/image.js:91:13)
    at PsImage.set (/www/wwwroot/fc/FFCreator-master/node_modules/canvas/lib/image.js:62:9)
    at BaseTexture.updateSource (/www/wwwroot/fc/FFCreator-master/node_modules/inkpaint/lib/textures/BaseTexture.js:58:20)
    at Texture.updateSource (/www/wwwroot/fc/FFCreator-master/node_modules/inkpaint/lib/textures/Texture.js:110:24)
    at Sprite.updateBaseTexture (/www/wwwroot/fc/FFCreator-master/node_modules/inkpaint/lib/sprites/Sprite.js:188:18)
    at FFVideo.drawing (/www/wwwroot/fc/FFCreator-master/lib/node/video.js:219:18)

**Comment by xeoshow** [comment]
@mcl0626 您好，请问您这个问题解决了吗？是如何解决的呢？非常感谢
