### ISSUE TITLE
forever 启动ffcreator报错

### ISSUE THREAD

**Issue by mcl0626** [tnfe/FFCreator#200]
(node:409516) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
FFCreator start
(node:409525) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ARRAY_BUFFER' of null
    at FFTransition.createBuffer (/www/wwwroot/easy/FFCreator-master/lib/animate/transition.js:73:45)
    at FFTransition.createTransition (/www/wwwroot/easy/FFCreator-master/lib/animate/transition.js:61:10)
    at FFTransition.bindGL (/www/wwwroot/easy/FFCreator-master/lib/animate/transition.js:40:10)
    at /www/wwwroot/easy/FFCreator-master/lib/core/renderer.js:119:57
    at arrayEach (/www/wwwroot/easy/FFCreator-master/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/www/wwwroot/easy/FFCreator-master/node_modules/lodash/forEach.js:38:10)
    at Renderer.transBindGL (/www/wwwroot/easy/FFCreator-master/lib/core/renderer.js:119:5)
    at Renderer.start (/www/wwwroot/easy/FFCreator-master/lib/core/renderer.js:55:10)
(Use `node --trace-warnings ...` to show where the warning was created)

启动命令：xvfb-run -s "-ac -screen 0 1280x1024x24" forever start app.js 这个命令报上边的错

非后台启动： xvfb-run -s "-ac -screen 0 1280x1024x24" node app.js  这个命令是没有问题，可以制作的

哪位大神指导一下

**Comment by drawcall** [comment]
xvfb-run -s "-ac -screen 0 1280x1024x24" npm start

**Comment by mcl0626** [comment]
node v14.18.3  centos7

ffmpeg version N-105287-g7d377558a6 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 8 (GCC)
configuration: --prefix=/root/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --extra-libs=-lpthread --extra-libs=-lm --bindir=/root/bin --enable-gpl --enable-libfdk_aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
libavutil      57. 18.100 / 57. 18.100
libavcodec     59. 20.100 / 59. 20.100
libavformat    59. 17.101 / 59. 17.101
libavdevice    59.  5.100 / 59.  5.100
libavfilter     8. 25.100 /  8. 25.100
libswscale      6.  5.100 /  6.  5.100
libswresample   4.  4.100 /  4.  4.100
libpostproc    56.  4.100 / 56.  4.100
