### ISSUE TITLE
请问什么时候能支持视频打马赛克的功能？

### ISSUE THREAD

**Issue by 851689968** [tnfe/FFCreator#207]
请问什么时候能支持视频打马赛克的功能？

**Comment by MrHao123** [comment]
大佬，我想咨询下。这个组件必须得用node10吗？我的安装完成 引入后一直报：
` TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
      at promisify (internal/util.js:206:11)
      at Object.<anonymous> (D:\vue\electron-vue-exe\node_modules\mtempy\index.js:12:18)
      at Object.<anonymous> (D:\vue\electron-vue-exe\node_modules\mtempy\index.js:78:3)
      at Module._compile (module.js:642:30)
      at Object.Module._extensions..js (module.js:653:10)
      at Module.load (module.js:561:32)
      at tryModuleLoad (module.js:504:12)
      at Function.Module._load (module.js:496:3)
      at Module.require (module.js:586:17)
      at require (internal/module.js:11:18)`
