### ISSUE TITLE
运行example里面自带的echart动态图表（name: 'Chart animation rendering video'）案例时报错。

### ISSUE THREAD

**Issue by muyuwuxin** [tnfe/FFCreator#220]
运行example里面自带的echart动态图表（name: 'Chart animation rendering video'）案例时报以下错误。求解决方法，谢谢！

D:\download\FFCreator-master\FFCreator-master\lib\node\chart.js:179
        this.onframe(delta);
             ^

TypeError: this.onframe is not a function
    at Animation.animation.update (D:\download\FFCreator-master\FFCreator-master\lib\node\chart.js:179:14)
    at Timeout.step [as _onTimeout] (D:\download\FFCreator-master\FFCreator-master\node_modules\echarts\dist\echarts.js:4508:43)
    at listOnTimeout (internal/timers.js:554:17)

**Comment by muyuwuxin** [comment]
> 

没有啊，5.1.2

**Comment by muyuwuxin** [comment]
> 是否自行升级了echarts?

检查了下，确实是多个文件夹的echart包搞混了，感谢回答，已解决。谢谢！
