### ISSUE TITLE
FFCreator error: _fs is not defined

### ISSUE THREAD

**Issue by KevinAtlans** [tnfe/FFCreator#258]
`
FFCreator error: _fs is not defined
FFEvent {
  type: 'error',
  pos: 'preProcessing',
  error: '_fs is not defined'
}
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg exited with code 1: Output #0, mp4, to '0od1d9botyiswztk.mp4':
Output file #0 does not contain any stream

    at ChildProcess.<anonymous> (/Users/admin/workspace/self/video-factory/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
Emitted 'error' event on FfmpegCommand instance at:
    at emitEnd (/Users/admin/workspace/self/video-factory/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at endCB (/Users/admin/workspace/self/video-factory/node_modules/fluent-ffmpeg/lib/processor.js:544:13)
    at handleExit (/Users/admin/workspace/self/video-factory/node_modules/fluent-ffmpeg/lib/processor.js:170:11)
    at ChildProcess.<anonymous> (/Users/admin/workspace/self/video-factory/node_modules/fluent-ffmpeg/lib/processor.js:182:11)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

执行突然抱错，然后就再也用不了了，之前都还可以用

**Comment by KevinAtlans** [comment]
I've solved it

**Comment by kxxoling** [comment]
@KevinAtlans 请问是什么问题？我这边也突然报错了。

**Comment by Laixinsz** [comment]
我也遇到了这个问题，你是怎么解决的？

**Comment by Laixinsz** [comment]
node_modules/inkpaint/lib/resource是这个依赖目录里有个Resource.js中有个_fs 没有定义直接引用导致的

**Comment by drawcall** [comment]
upgrade fs-extra
