### ISSUE TITLE
npm start 无法启动项目

### ISSUE THREAD

**Issue by lcllge** [tnfe/FFCreator#276]
本人Windows 环境, 有显卡, 项目install之后, 可以运行npm run examples 命令, 但是文档所说的npm start无法运行, 报错信息为找不到npm start命令, 同时package.json的scripts里面也没有相关命令的配置, 文档是否有问题, 还是得打开的方式不对

0 verbose cli C:\Program Files\nodejs\node.exe D:\nodejs\node_global\node_modules\npm\bin\npm-cli.js
1 info using npm@8.18.0
2 info using node@v16.17.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:D:\nodejs\node_global\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:D:\workspace\FFCreator-6.7.1\.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:D:\Users\W9080814\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:D:\nodejs\node_global\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 timing npm:load:configload Completed in 12ms
20 timing npm:load:mkdirpcache Completed in 0ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm start
23 verbose argv "start"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 2ms
26 timing npm:load:display Completed in 3ms
27 verbose logfile logs-max:10 dir:D:\nodejs\node_cache\_logs
28 verbose logfile D:\nodejs\node_cache\_logs\2022-09-20T02_45_58_523Z-debug-0.log
29 timing npm:load:logFile Completed in 4ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 22ms
33 silly logfile start cleaning logs, removing 2 files
34 silly logfile done cleaning log files
35 timing command:run-script Completed in 7ms
36 timing command:start Completed in 11ms
37 verbose stack Error: Missing script: "start"
37 verbose stack
37 verbose stack Did you mean one of these?
37 verbose stack     npm star # Mark your favorite packages
37 verbose stack     npm stars # View packages marked as favorites
37 verbose stack
37 verbose stack To see a list of scripts, run:
37 verbose stack   npm run
37 verbose stack     at RunScript.run (D:\nodejs\node_global\node_modules\npm\lib\commands\run-script.js:98:13)
37 verbose stack     at async module.exports (D:\nodejs\node_global\node_modules\npm\lib\cli.js:78:5)
38 verbose cwd D:\workspace\FFCreator-6.7.1
39 verbose Windows_NT 10.0.19044
40 verbose node v16.17.0
41 verbose npm  v8.18.0
42 error Missing script: "start"
42 error
42 error Did you mean one of these?
42 error     npm star # Mark your favorite packages
42 error     npm stars # View packages marked as favorites
42 error
42 error To see a list of scripts, run:
42 error   npm run
43 verbose exit 1
44 timing npm Completed in 46ms
45 verbose code 1
46 error A complete log of this run can be found in:
46 error     D:\nodejs\node_cache\_logs\2022-09-20T02_45_58_523Z-debug-0.log

**Comment by drawcall** [comment]
https://tnfe.github.io/FFCreator/#/qa/qa

**Comment by zdu-strong** [comment]
你可以克隆这个项目, 在此目录下直接运行 npm start 即可生成视频. 
src目录下是代码, 可以进行编辑.

https://github.com/zdu-strong/Technical_Backup/tree/master/ffcreator
