### ISSUE TITLE
Critical error when using the api to create the video

### ISSUE THREAD

**Issue by xeoshow** [tnfe/FFCreator#280]
The logs are as below, not sure why, and still will reach to the event  of creator.on('complete' ... 
Any one could please kindly help? Thanks a lot.

===
5|worker  | 2022-09-30 10:20:39: TypeError: Cannot read property 'getFrame' of null
5|worker  |     at FFGifImage.drawing (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+ffcreator@6.7.2/node_modules/ffcreator/lib/node/gif.js:170:36)
5|worker  |     at /mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+ffcreator@6.7.2/node_modules/ffcreator/lib/timeline/update.js:38:29
5|worker  |     at arrayEach (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+lodash@4.17.21/node_modules/lodash/_arrayEach.js:15:9)
5|worker  |     at forEach (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+lodash@4.17.21/node_modules/lodash/forEach.js:38:10)
5|worker  |     at Object.update (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+ffcreator@6.7.2/node_modules/ffcreator/lib/timeline/update.js:38:5)
5|worker  |     at Timeline.nextFrame (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+ffcreator@6.7.2/node_modules/ffcreator/lib/timeline/timeline.js:183:22)
5|worker  |     at Renderer.renderFrame (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+ffcreator@6.7.2/node_modules/ffcreator/lib/core/renderer.js:186:14)
5|worker  |     at FFStream.fillNewData (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+ffcreator@6.7.2/node_modules/ffcreator/lib/utils/stream.js:49:31)
5|worker  |     at FFStream._read (/mnt/sfs/project/node_modules/.pnpm/registry.npmmirror.com+ffcreator@6.7.2/node_modules/ffcreator/lib/utils/stream.js:61:32)
5|worker  |     at FFStream.Readable.read (internal/streams/readable.js:481:10)

**Comment by drawcall** [comment]
Please check the gif images are different? It seems gif img parsing failed.

**Comment by xeoshow** [comment]
Thanks for quick reply. They are just normal gif images. Is there any special requirement for the gif file? Or any check method for doing this?
Or, at least we could throw this error to the ffcreator to avoid the bad video creation?
Thanks again.

Best regards, Jason
