### ISSUE TITLE
help:lottie,Image given has not completed loading

### ISSUE THREAD

**Issue by Codeprh** [tnfe/FFCreator#287]
## 问题描述

当我使用ae导出的lottie可以处理的json文件的时候。运行example/lottie.js，基于例子做了最小修改。

```javascript
const path = require('path');
const colors = require('colors');
const startAndListen = require('./listen');
const {FFCreatorCenter, FFScene, FFImage, FFLottie, FFCreator} = require('../');

const createFFTask = () => {
  const file1 = path.join(__dirname, './assets/lottie/data.json');
  const outputDir = path.join(__dirname, './output/');
  const cacheDir = path.join(__dirname, './cache/');

  // create creator instance
  const width = 1920;
  const height = 1080;
  const creator = new FFCreator({
    cacheDir,
    outputDir,
    width,
    height
  });

  // create FFScene
  const scene = new FFScene();
  const flottie1 = new FFLottie({
    x: width / 2,
    y: height / 2,
    width,
    height,
    file: file1,
    loop: false,
  });
  scene.addChild(flottie1);

  scene.setDuration(18);
  creator.addChild(scene);
  creator.start();

  creator.on('start', () => {
    console.log(`FFCreator start`);
  });

  creator.on('error', e => {
    console.log(colors.red(`FFCreator error: ${e.error}`));
  });

  creator.on('progress', e => {
    console.log(colors.yellow(`FFCreator progress: ${(e.percent * 100) >> 0}%`));
  });

  creator.on('complete', e => {
    console.log(
      colors.magenta(`FFCreator completed: \n USEAGE: ${e.useage} \n PATH: ${e.output} `),
    );

    console.log(colors.green(`\n --- You can press the s key or the w key to restart! --- \n`));
  });

  return creator;
};

module.exports = () => startAndListen(() => FFCreatorCenter.addTask(createFFTask));

```

- 我使用的json，我上传到了阿里云盘
  - 链接: https://pan.baidu.com/s/1g4JvhGI6AGAWWSV2dCGDmA 提取码: 1qhk
- 我发现的问题，当我使用小文件，几KB的图片去运行的时候没问题，当图片比较大的时候，比如10MB，就会报错。
- 最后生成的没有任何动画的mp4文件。
- 希望大佬可以帮忙小弟看看。

## 错误信息json

```javascript
Error: Image given has not completed loading
    at CVImageElement.renderInnerContent (/Users/noah/Documents/noah/gitlab-font/ffCreator/FFCreator/node_modules/lottie-nodejs/build/lottie_canvas.js:7760:22)
    at CVImageElement.renderFrame (/Users/noah/Documents/noah/gitlab-font/ffCreator/FFCreator/node_modules/lottie-nodejs/build/lottie_canvas.js:7690:10)
    at CanvasRenderer.renderFrame (/Users/noah/Documents/noah/gitlab-font/ffCreator/FFCreator/node_modules/lottie-nodejs/build/lottie_canvas.js:6245:26)
    at AnimationItem.renderFrame (/Users/noah/Documents/noah/gitlab-font/ffCreator/FFCreator/node_modules/lottie-nodejs/build/lottie_canvas.js:9118:19)
    at AnimationItem.gotoFrame (/Users/noah/Documents/noah/gitlab-font/ffCreator/FFCreator/node_modules/lottie-nodejs/build/lottie_canvas.js:9111:8)
    at AnimationItem.setCurrentRawFrameAndGoto (/Users/noah/Documents/noah/gitlab-font/ffCreator/FFCreator/node_modules/lottie-nodejs/build/lottie_canvas.js:9341:8)
    at AnimationItem.advanceTime (/Users/noah/Documents/noah/gitlab-font/ffCreator/FFCreator/node_modules/lottie-nodejs/build/lottie_canvas.js:9229:10)
    at AnimationItem.render (/Users/noah/Documents/noah/gitlab-font/ffCreator/FFCreator/node_modules/lottie-nodejs/build/lottie_canvas.js:9356:8)
    at FFLottie.updateCallback (/Users/noah/Documents/noah/gitlab-font/ffCreator/FFCreator/lib/node/lottie.js:146:14)
    at /Users/noah/Documents/noah/gitlab-font/ffCreator/FFCreator/lib/timeline/update.js:38:29
```

## 重现步骤

https://img.noahpan.cn/img-2022/202210130057546.png

- 环境安装：git clone项目->npm i
- 链接: https://pan.baidu.com/s/1g4JvhGI6AGAWWSV2dCGDmA 提取码: 1qhk
  - 从链接下载到的资源，放到lottie资源目录下。
- 运行node index.js，选择16

https://img.noahpan.cn/img-2022/202210130059379.png

**Comment by drawcall** [comment]
Oh, can you use lottie-node to run and check error
https://github.com/drawcall/lottie-node

**Comment by ChengZhiPeng** [comment]
我的代码跟你类似   也是读取json 转成视频  就是想改json里面的图片资源会出现 [help:lottie,Image given has not completed loading]这个问题
