### ISSUE TITLE
部署到 linux 服务器上启动后未找到 webgl

### ISSUE THREAD

**Issue by chin-ray** [tnfe/FFCreator#299]
/server/node_modules/ffcreator/lib/animate/transition.js:73
    this.buffer = createBuffer(gl, data, gl.ARRAY_BUFFER, gl.STATIC_DRAW);
                                            ^

TypeError: Cannot read properties of null (reading 'ARRAY_BUFFER')
    at FFTransition.createBuffer (/data/marathon/h5/server/node_modules/ffcreator/lib/animate/transition.js:73:45)
    at FFTransition.createTransition (/data/marathon/h5/server/node_modules/ffcreator/lib/animate/transition.js:61:10)
    at FFTransition.bindGL (/data/marathon/h5/server/node_modules/ffcreator/lib/animate/transition.js:40:10)
    at /data/marathon/h5/server/node_modules/ffcreator/lib/core/renderer.js:122:57
    at arrayEach (/data/marathon/h5/server/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/data/marathon/h5/server/node_modules/lodash/forEach.js:38:10)
    at Renderer.transBindGL (/data/marathon/h5/server/node_modules/ffcreator/lib/core/renderer.js:122:5)
    at Renderer.start (/data/marathon/h5/server/node_modules/ffcreator/lib/core/renderer.js:55:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by drawcall** [comment]
https://tnfe.github.io/FFCreator/#/qa](https://tnfe.github.io/FFCreator/#/qa/

**Comment by drawcall** [comment]
Help test If compatible with old ffcreator version

**Comment by chin-ray** [comment]
> 

地址失效了

**Comment by bobsam** [comment]
@chin-ray https://tnfe.github.io/FFCreator/#/qa/qa
