### ISSUE TITLE
new FFImage file name does not support Chinese?中文名就报错了

### ISSUE THREAD

**Issue by gclsoft** [tnfe/FFCreator#3]
```
  const img = path.join(__dirname, `./assets/imgs/trans/一0${index}.jpeg`);
  const bg = new FFImage({path: img, resetXY: true});
  scene.addChild(bg);

  // title text
  const ftext = new FFText({text, x: width / 2, y: height / 2 + 50, fontSize: 38});
  ftext.setColor('#30336b');
  ftext.alignCenter();
  ftext.setBackgroundColor('#ffffff');
  ftext.addEffect('fadeInRight', 1, 1.3);
  ftext.setStyle({padding: [4, 12, 6, 12]});
  scene.addChild(ftext);
```
```
(node:9836) ExperimentalWarning: The fs.promises API is experimental
(node:9836) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'C:\Users\asus\FFCreator\examples\assets\imgs\trans\一01.jpeg'
    at setSource (C:\Users\asus\FFCreator\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\asus\FFCreator\node_modules\canvas\lib\image.js:62:9)
    at Promise (C:\Users\asus\FFCreator\node_modules\canvas\index.js:34:15)
    at new Promise (<anonymous>)
    at loadImage (C:\Users\asus\FFCreator\node_modules\canvas\index.js:23:10)
    at Object.ENV.loadImage (C:\Users\asus\FFCreator\node_modules\spritejs\lib\platform\node-canvas.js:38:43)
    at loadTexture (C:\Users\asus\FFCreator\node_modules\spritejs\dist\spritejs.js:28552:63)
    at _callee$ (C:\Users\asus\FFCreator\node_modules\spritejs\dist\spritejs.js:28573:30)
    at tryCatch (C:\Users\asus\FFCreator\node_modules\spritejs\dist\spritejs.js:10088:40)
    at Generator.invoke [as _invoke] (C:\Users\asus\FFCreator\node_modules\spritejs\dist\spritejs.js:10318:22)
(node:9836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:9836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9836) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'C:\Users\asus\FFCreator\examples\assets\imgs\trans\一01.jpeg'
    at setSource (C:\Users\asus\FFCreator\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\asus\FFCreator\node_modules\canvas\lib\image.js:62:9)
    at Promise (C:\Users\asus\FFCreator\node_modules\canvas\index.js:34:15)
    at new Promise (<anonymous>)
    at loadImage (C:\Users\asus\FFCreator\node_modules\canvas\index.js:23:10)
    at Object.ENV.loadImage (C:\Users\asus\FFCreator\node_modules\spritejs\lib\platform\node-canvas.js:38:43)
    at loadTexture (C:\Users\asus\FFCreator\node_modules\spritejs\dist\spritejs.js:28552:63)
    at _callee$ (C:\Users\asus\FFCreator\node_modules\spritejs\dist\spritejs.js:28573:30)
    at tryCatch (C:\Users\asus\FFCreator\node_modules\spritejs\dist\spritejs.js:10088:40)
    at Generator.invoke [as _invoke] (C:\Users\asus\FFCreator\node_modules\spritejs\dist\spritejs.js:10318:22)
(node:9836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:9836) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'C:\Users\asus\FFCreator\examples\assets\imgs\trans\一02.jpeg'
```

**Comment by drawcall** [comment]
Oh, I don’t think so. Is your file naming wrong or different?

**Comment by gclsoft** [comment]
![image](https://user-images.githubusercontent.com/1269898/99178542-08e42080-274f-11eb-990f-f88ae06a80b0.png)
@drawcall The file nameing is right. It can't contain any Chinese words

**Comment by gclsoft** [comment]
The same on win10:
```
"C:\Program Files\nodejs\node.exe" C:\work\newml\ffcreator\examples\transition.js
(node:20788) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'C:\work\newml\ffcreator\examples\assets\imgs\trans\一01.jpeg'
    at setSource (C:\work\newml\ffcreator\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\work\newml\ffcreator\node_modules\canvas\lib\image.js:62:9)
    at C:\work\newml\ffcreator\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\work\newml\ffcreator\node_modules\canvas\index.js:23:10)
    at Object.ENV.loadImage (C:\work\newml\ffcreator\node_modules\spritejs\lib\platform\node-canvas.js:38:43)
    at loadTexture (C:\work\newml\ffcreator\node_modules\spritejs\dist\spritejs.js:28552:63)
    at _callee$ (C:\work\newml\ffcreator\node_modules\spritejs\dist\spritejs.js:28573:30)
    at tryCatch (C:\work\newml\ffcreator\node_modules\spritejs\dist\spritejs.js:10088:40)
    at Generator.invoke [as _invoke] (C:\work\newml\ffcreator\node_modules\spritejs\dist\spritejs.js:10318:22)
(node:20788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:20788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:20788) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'C:\work\newml\ffcreator\examples\assets\imgs\trans\一01.jpeg'
    at setSource (C:\work\newml\ffcreator\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\work\newml\ffcreator\node_modules\canvas\lib\image.js:62:9)
    at C:\work\newml\ffcreator\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\work\newml\ffcreator\node_modules\canvas\index.js:23:10)
    at Object.ENV.loadImage (C:\work\newml\ffcreator\node_modules\spritejs\lib\platform\node-canvas.js:38:43)
    at loadTexture (C:\work\newml\ffcreator\node_modules\spritejs\dist\spritejs.js:28552:63)
    at _callee$ (C:\work\newml\ffcreator\node_modules\spritejs\dist\spritejs.js:28573:30)
    at tryCatch (C:\work\newml\ffcreator\node_modules\spritejs\dist\spritejs.js:10088:40)
    at Generator.invoke [as _invoke] (C:\work\newml\ffcreator\node_modules\spritejs\dist\spritejs.js:10318:22)
(node:20788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:20788) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'C:\work\newml\ffcreator\examples\assets\imgs\trans\一02.jpeg'
    at setSource (C:\work\newml\ffcreator\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\work\newml\ffcreator\node_modules\canvas\lib\image.js:62:9)
    at C:\work\newml\ffcreator\node_modules\canvas\index.js:34:15
```

**Comment by gclsoft** [comment]
on win7, other file names:
```
C:\Work2\nodejs2\node.exe C:\Users\asus\FFCreator\examples\make.js
(node:6528) ExperimentalWarning: The fs.promises API is experimental
[FF] Creator production error. Right-hand side of 'instanceof' is not an object
(node:6528) UnhandledPromiseRejectionWarning: Error: EILSEQ, Illegal byte sequence 'C:\Users\asus\FFCreator\examples\assets\res\1937年，延安2.jpg'
    at setSource (C:\Users\asus\FFCreator\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\asus\FFCreator\node_modules\canvas\lib\image.js:62:9)
    at Promise (C:\Users\asus\FFCreator\node_modules\canvas\index.js:34:15)
    at new Promise (<anonymous>)
    at loadImage (C:\Users\asus\FFCreator\node_modules\canvas\index.js:23:10)
    at Object.ENV.loadImage (C:\Users\asus\FFCreator\node_modules\spritejs\lib\platform\node-canvas.js:38:43)
    at loadTexture (C:\Users\asus\FFCreator\node_modules\spritejs\dist\spritejs.js:28552:63)
    at _callee$ (C:\Users\asus\FFCreator\node_modules\spritejs\dist\spritejs.js:28573:30)
    at tryCatch (C:\Users\asus\FFCreator\node_modules\spritejs\dist\spritejs.js:10088:40)
    at Generator.invoke [as _invoke] (C:\Users\asus\FFCreator\node_modules\spritejs\dist\spritejs.js:10318:22)
(node:6528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6528) UnhandledPromiseRejectionWarning: Error: EILSEQ, Illegal byte sequence 'C:\Users\asus\FFCreator\examples\assets\res\1937年，延安.jpg'
```

**Comment by fantasticsoul** [comment]
try https://github.com/jprichardson/node-fs-extra?

**Comment by drawcall** [comment]
Oh, it should be the reason why the C++ method `fopen` cannot open the Chinese path [https://github.com/Automattic/node-canvas/blob/master/src/Image.cc](https://github.com/Automattic/node-canvas/blob/master/src/Image.cc). So I suggest you use English path, or if you really want to use Chinese, please use iconv to convert GBK encoding.

**Comment by wujohns** [comment]
如果是win10的话可以把这个配置勾上就可以解决中文文件名的问题：
![1623412913(1)](https://user-images.githubusercontent.com/4157244/121683528-18aec200-caf0-11eb-83dd-a4f7bcc99363.png)

**Comment by wujohns** [comment]
主要原因是node-canvas读取文件时会统一按照utf-8方式，所以mac下时ok的，win下需要做上述配置调整
