### ISSUE TITLE
我遇到一些问题在 Apple Mac Mini M1 芯片上: `Error: Could not locate the bindings file.`

### ISSUE THREAD

**Issue by lorcannn** [tnfe/FFCreator#31]
电脑系统：Apple Mac Mini M1 芯片, macOs Big Sur 11.2.3
Node 环境：
```
node -v
v14.15.3

node
> process.arch
'x64'
> process.platform
'darwin'
> 
```
FFmpeg 已安装：
```
ffmpeg
ffmpeg version 4.3.2 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.29)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/4.3.2_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

当我运行代码后，控制台出现如下报错
```
> node index.js

/Users/lorcannn/code/project/short-video-creator/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /Users/lorcannn/code/project/short-video-creator/node_modules/gl/build/webgl.node
 → /Users/lorcannn/code/project/short-video-creator/node_modules/gl/build/Debug/webgl.node
 → /Users/lorcannn/code/project/short-video-creator/node_modules/gl/build/Release/webgl.node
 → /Users/lorcannn/code/project/short-video-creator/node_modules/gl/out/Debug/webgl.node
 → /Users/lorcannn/code/project/short-video-creator/node_modules/gl/Debug/webgl.node
 → /Users/lorcannn/code/project/short-video-creator/node_modules/gl/out/Release/webgl.node
 → /Users/lorcannn/code/project/short-video-creator/node_modules/gl/Release/webgl.node
 → /Users/lorcannn/code/project/short-video-creator/node_modules/gl/build/default/webgl.node
 → /Users/lorcannn/code/project/short-video-creator/node_modules/gl/compiled/14.15.3/darwin/x64/webgl.node
 → /Users/lorcannn/code/project/short-video-creator/node_modules/gl/addon-build/release/install-root/webgl.node
 → /Users/lorcannn/code/project/short-video-creator/node_modules/gl/addon-build/debug/install-root/webgl.node
 → /Users/lorcannn/code/project/short-video-creator/node_modules/gl/addon-build/default/install-root/webgl.node
 → /Users/lorcannn/code/project/short-video-creator/node_modules/gl/lib/binding/node-v83-darwin-x64/webgl.node
    at bindings (/Users/lorcannn/code/project/short-video-creator/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/Users/lorcannn/code/project/short-video-creator/node_modules/gl/src/javascript/native-gl.js:1:40)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/lorcannn/code/project/short-video-creator/node_modules/gl/src/javascript/webgl-rendering-context.js:4:58)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  tries: [
    '/Users/lorcannn/code/project/short-video-creator/node_modules/gl/build/webgl.node',
    '/Users/lorcannn/code/project/short-video-creator/node_modules/gl/build/Debug/webgl.node',
    '/Users/lorcannn/code/project/short-video-creator/node_modules/gl/build/Release/webgl.node',
    '/Users/lorcannn/code/project/short-video-creator/node_modules/gl/out/Debug/webgl.node',
    '/Users/lorcannn/code/project/short-video-creator/node_modules/gl/Debug/webgl.node',
    '/Users/lorcannn/code/project/short-video-creator/node_modules/gl/out/Release/webgl.node',
    '/Users/lorcannn/code/project/short-video-creator/node_modules/gl/Release/webgl.node',
    '/Users/lorcannn/code/project/short-video-creator/node_modules/gl/build/default/webgl.node',
    '/Users/lorcannn/code/project/short-video-creator/node_modules/gl/compiled/14.15.3/darwin/x64/webgl.node',
    '/Users/lorcannn/code/project/short-video-creator/node_modules/gl/addon-build/release/install-root/webgl.node',
    '/Users/lorcannn/code/project/short-video-creator/node_modules/gl/addon-build/debug/install-root/webgl.node',
    '/Users/lorcannn/code/project/short-video-creator/node_modules/gl/addon-build/default/install-root/webgl.node',
    '/Users/lorcannn/code/project/short-video-creator/node_modules/gl/lib/binding/node-v83-darwin-x64/webgl.node'
  ]
}
```

当我注释以下代码后，其他代码正常运行
```javascript
const {FFScene, FFImage, FFCreator} = require('ffcreator');
```

**Comment by drawcall** [comment]
It might happen when some libraries failed during installation (e.g. due to incompatible Node version)
Try rebuilding dependencies with npm rebuild
