### ISSUE TITLE
xvfb-run -s "-ac -screen 0 1280x1024x24" pm2 start bin/www -i 4

### ISSUE THREAD

**Issue by f1748x** [tnfe/FFCreator#322]
pm2 跑项目出以下错误:
0|www  | 开始生成视频: -------start---------
0|www  | TypeError: Cannot read property 'ARRAY_BUFFER' of null
0|www  |     at FFTransition.createBuffer (/volumn/ffmpeg/FFCreator/lib/animate/transition.js:73:45)
0|www  |     at FFTransition.createTransition (/volumn/ffmpeg/FFCreator/lib/animate/transition.js:61:10)
0|www  |     at FFTransition.bindGL (/volumn/ffmpeg/FFCreator/lib/animate/transition.js:40:10)
0|www  |     at /volumn/ffmpeg/FFCreator/lib/core/renderer.js:122:57
0|www  |     at arrayEach (/volumn/ffmpeg/node_modules/lodash/_arrayEach.js:15:9)
0|www  |     at forEach (/volumn/ffmpeg/node_modules/lodash/forEach.js:38:10)
0|www  |     at Renderer.transBindGL (/volumn/ffmpeg/FFCreator/lib/core/renderer.js:122:5)
0|www  |     at Renderer.start (/volumn/ffmpeg/FFCreator/lib/core/renderer.js:55:10)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)

---------------------------------------------------------

怎么解决啊

**Comment by drawcall** [comment]
https://tnfe.github.io/FFCreator/#/qa/qa
Please Read QA

**Comment by zdu-strong** [comment]
删除一部分参数即可修复这个bug.
xvfb-run pm2 start bin/www -i 4
