### ISSUE TITLE
Cannot read property 'updateBaseTexture' of null

### ISSUE THREAD

**Issue by xeoshow** [tnfe/FFCreator#352]
请教下：使用时遇到下面问题，是因为highWaterMark 设置不当吗？目前用的默认值(应该是1mb)，需要调大还是调小呢？谢谢
![image](https://user-images.githubusercontent.com/1164284/235875749-549b055a-701d-454d-98ca-eca13a3699c3.png)
2023-05-03 13:47:38: [32m[FF] Synthesis synthesis start: ffmpeg -f rawvideo -framerate 30 -s 720x1280 -vcodec rawvideo -pixel_format bgra -video_size 720x1280 -i pipe:0 -stream_loop -1 -i /mnt/sfs/project/public/system/audio/快乐26.mp3 -i /mnt/sfs/project/public/output/cache/trgMiTMM2kkjr3MZGX3Qk.mp3 -y -filter_complex [1]adelay=0|0[audio0];[2]adelay=0|0[audio1];[audio0][audio1]amix=2 -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -r 30 -c:a aac -t 9.843 /mnt/sfs/project/public/output/video/e33c29rfc7n38gl4.mp4[39m
2023-05-03 13:47:38: [32m[FF] renderFrame current frame - 0[39m
2023-05-03 13:47:38: TypeError: Cannot read property 'updateBaseTexture' of null
    at FFVideo.drawing (/mnt/sfs/project/node_modules/.pnpm/ffcreator@6.7.5/node_modules/ffcreator/lib/node/video.js:219:18)
    at /mnt/sfs/project/node_modules/.pnpm/ffcreator@6.7.5/node_modules/ffcreator/lib/timeline/update.js:38:29
    at arrayEach (/mnt/sfs/project/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/mnt/sfs/project/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/forEach.js:38:10)
    at Object.update (/mnt/sfs/project/node_modules/.pnpm/ffcreator@6.7.5/node_modules/ffcreator/lib/timeline/update.js:38:5)
    at Timeline.nextFrame (/mnt/sfs/project/node_modules/.pnpm/ffcreator@6.7.5/node_modules/ffcreator/lib/timeline/timeline.js:183:22)
    at Renderer.renderFrame (/mnt/sfs/project/node_modules/.pnpm/ffcreator@6.7.5/node_modules/ffcreator/lib/core/renderer.js:186:14)
    at FFStream.fillNewData (/mnt/sfs/project/node_modules/.pnpm/ffcreator@6.7.5/node_modules/ffcreator/lib/utils/stream.js:49:31)
    at FFStream._read (/mnt/sfs/project/node_modules/.pnpm/ffcreator@6.7.5/node_modules/ffcreator/lib/utils/stream.js:61:32)
    at FFStream.Readable.read (internal/streams/readable.js:481:10)

**Comment by drawcall** [comment]
https://github.com/tnfe/FFCreator/issues/311
