### ISSUE TITLE
Support for Bun

### ISSUE THREAD

**Issue by nachat-ayoub** [tnfe/FFCreator#445]
the library does not work with bun, i think the cause is node-canvas is not compatible with Bun because they have their own implementation @napi-rs/canvas.

**Comment by drawcall** [comment]
This error occurs because the Node WebGL module you are using is compiled for a different Node.js ABI version, while the current version of Bun you are using requires a different ABI version.  try 'npm rebuild gl'

**Comment by nachat-ayoub** [comment]
@drawcall I did that and still getting the same error. can you try running a ts file that uses the FFCreator package with bun and update me with a solution?

i even tried using this command:

```bash
$env:npm_config_target = 'v21.7.3';
> bun install
```
but got this error:

error: Could not locate the bindings file. Tried:
 → C:\Users\...\elysia-app\node_modules\gl\build\webgl.node
 → C:\Users\...\elysia-app\node_modules\gl\build\Debug\webgl.node
 → C:\Users\...\elysia-app\node_modules\gl\build\Release\webgl.node
 → C:\Users\...\elysia-app\node_modules\gl\out\Debug\webgl.node
 → C:\Users\...\elysia-app\node_modules\gl\Debug\webgl.node
 → C:\Users\...\elysia-app\node_modules\gl\out\Release\webgl.node
 → C:\Users\...\elysia-app\node_modules\gl\Release\webgl.node
 → C:\Users\...\elysia-app\node_modules\gl\build\default\webgl.node
 → C:\Users\...\elysia-app\node_modules\gl\compiled\22.6.0\win32\x64\webgl.node
 → C:\Users\...\elysia-app\node_modules\gl\addon-build\release\install-root\webgl.node
 → C:\Users\...\elysia-app\node_modules\gl\addon-build\debug\install-root\webgl.node
 → C:\Users\...\elysia-app\node_modules\gl\addon-build\default\install-root\webgl.node
 → C:\Users\...\elysia-app\node_modules\gl\lib\binding\node-v127-win32-x64\webgl.node
      at bindings (C:\Users\...\elysia-app\node_modules\bindings\bindings.js:126:9)
      at C:\Users\...\elysia-app\node_modules\gl\src\javascript\native-gl.js:1:7
      at C:\Users\...\elysia-app\node_modules\gl\src\javascript\webgl-rendering-context.js:4:42
      at C:\Users\...\elysia-app\node_modules\gl\src\javascript\node-index.js:3:32
      at C:\Users\...\elysia-app\node_modules\gl\index.js:4:10
      at C:\Users\...\elysia-app\node_modules\inkpaint\lib\canvas-gl.js:120:11
      at C:\Users\...\elysia-app\node_modules\inkpaint\lib\polyfill\Canvas.js:7:5
      at C:\Users\...\elysia-app\node_modules\inkpaint\lib\polyfill\Doc.js:8:15
      at C:\Users\...\elysia-app\node_modules\inkpaint\lib\renderers\SystemRenderer.js:11:12
      at C:\Users\...\elysia-app\node_modules\inkpaint\lib\renderers\canvas\CanvasRenderer.js:7:23
      at C:\Users\...\elysia-app\node_modules\inkpaint\lib\core.js:318:23
      at C:\Users\...\elysia-app\node_modules\inkpaint\lib\index.js:480:5
      at C:\Users\...\elysia-app\node_modules\ffcreator\lib\node\cons.js:16:20
      at C:\Users\...\elysia-app\node_modules\ffcreator\lib\creator.js:23:7
      at C:\Users\...\elysia-app\node_modules\ffcreator\lib\index.js:14:7

Bun v1.1.29 (Windows x64)
Nodejs v21.7.3

**Comment by drawcall** [comment]
Sorry, too busy at work. try again later.

**Comment by nachat-ayoub** [comment]
> Sorry, too busy at work. try again later.

Thanks for replying, i will wait until Bun team support the nodejs latest version.

**Comment by drawcall** [comment]
or cd node_modules/gl
node-gyp rebuild
